apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${app-name}-backend
  namespace: ${namespace}
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  rules:
  - host: ${backend-external-host} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${app-name}-backend 
            port:
              number: 4000 
---
apiVersion: v1
kind: Service
metadata:
  name: ${app-name}-backend
  namespace: ${namespace} 
spec:
  selector:
    app: ${app-name}-backend
  ports:
  - name: ${app-name}-backend
    protocol: TCP
    port: 4000 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ${app-name}-backend
  namespace: ${namespace} 
  labels:
    app:  ${app-name}-backend
spec:
  selector:
    matchLabels:
      app: ${app-name}-backend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ${app-name}-backend
    spec:
      containers:
      - name:  ${app-name}-backend
        image:  ${image-name-base}-backend:${image-tag}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: PGHOST 
          value: ${postgresql-host}
        - name: PGDATABASE 
          value: ${postgresql-database}
        - name: GRAPHILE_PASSWORD 
          value: ${graphile-password}
        - name: GRAPHILE_JWT_SECRET 
          value: ${graphile-jwt-secret}
        ports:
        - containerPort: 4000 
          name:  ${app-name}-backend
      restartPolicy: Always