require:
  - ts-node/register/transpile-only
additionalResolvers:
  - ./src/additional-resolvers/index.ts  
sources:
  - name: database 
    handler:
      postgraphile:
        connectionString: postgres://graphile:${GRAPHILE_PASSWORD}@${PGHOST}:5432/${PGDATABASE}
        cacheIntrospection: true
        appendPlugins:
          - '@graphile-contrib/pg-simplify-inflector'
        schemaName:
          - app_public 
        options:
          dynamicJson: true
          watchPg: true
          setofFunctionsContainNulls: false
          ignoreRBAC: false
          ignoreIndexes: false
          enableQueryBatching: true
          legacyRelations: omit
          subscriptions: true
          retryOnInitFail: true
          simpleCollections: both
          extendErrors:
            - errcode
          graphiql: true 
          disableQueryLog: true
          jwtVerifyOptions:
            ignoreExpiration: false
          default_role: graphile_visitor 
          jwtSecret: ${GRAPHILE_JWT_SECRET}
          jwtPgTypeIdentifier: app_public.jwt_token