apiVersion: batch/v1
kind: Job
metadata:
  name: ${app-name}-database
  namespace: ${namespace}
  labels:
    app: ${app-name}-database
spec:
  template:
    metadata:
      name: ${app-name}-database
      labels:
        app: ${app-name}-database
    spec:
      containers:
      - name: ${app-name}-database
        image: python:3.7.6-alpine3.10
        command: ['sh', '-c', 'python3 manage.py makemigrations && python3 manage.py migrate']
        env:
        - name: ENV_NAME
          value: ENV_VALUE
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst