apiVersion: v1
kind: Service
metadata:
  name: ${app-name}-frontend
  namespace: ${namespace}
spec:
  selector:
    app: ${app-name}-frontend
  type: LoadBalancer 
  ports:
  - name: ${app-name}-frontend
    protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ${app-name}-frontend
  namespace: ${namespace}
  labels:
    app:  ${app-name}-frontend
spec:
  selector:
    matchLabels:
      app: ${app-name}-frontend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ${app-name}-frontend
    spec:
      containers:
      - name:  ${app-name}-frontend
        image:  ${image-name-base}-frontend:${image-tag}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
          - name: REACT_APP_GRAPHQL_URI
            value: ${react-app-graphql-uri}
        ports:
        - containerPort: 3000 
          name:  ${app-name}-frontend
      restartPolicy: Always